version: '2'
services:
    restaurationchapel-app:
        image: restaurationchapel
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://restaurationchapel-mysql:3306/restaurationchapel?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    restaurationchapel-mysql:
        extends:
            file: mysql.yml
            service: restaurationchapel-mysql
